### ISSUE TITLE
Map UI Buglets (24/06/19)

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#147]
Full Screen:
- [x] 1 Inititative does not deselect in the sidebar when a new icon is selected on the map.
- [ ] 2 Activities not being displayed in popup. REPLACED WITH [this](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/150)
- [x] 3 '(oxford)' text is being displayed in small bubble when hovering. Remove?
- [x] 4 If both panels are open (full screen) and an inititive is selected that happens to be behind the panel, the map does not pan to reveal it. I imagine this might be tricky to fix, so if it can't automatically detect that that has happened, is there another clue that could be given?!
- [x] 5 The show sidebar tab should say hide sidebar when the panel is pulled out.

Mobile:
 - [x] 1 Seleting an inititave by clicking its icon does not display the inititiave's details in the side panel.
 - [ ]  2 As we are now 3 panels 'deep' when displaying an init's details, it would be very nice to have another tab which collapses all panels. REPLACED WITH [this](https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/177)
- [x] 3 When selecting an init from the sidepanel and it is already visible on the map, and there are other inits visible, there is nothing to indicate which one it is. Could we display the name bubble that usually only appears when you hover for a second? Is is possible to display that bubble 'above' the panels for a second, to also address #4 in the Full Screen bug list.

**Comment by joebillings** [comment]
I'm not seeing 3. Is it just when you're hovering over the map? Is it a browser tooltip or styled like the ones that appear when hovering over the markers?

**Comment by ColmMassey** [comment]
> I'm not seeing 3. Is it just when you're hovering over the map? Is it a browser tooltip or styled like the ones that appear when hovering over the markers?

This is v minor. 
![Bubble](https://user-images.githubusercontent.com/1162642/60089229-f1f6f580-9737-11e9-8007-4cf98a149c6a.png)

**Comment by joebillings** [comment]
Aha! Not sure how I missed that!
